[build]
builder = "nixpacks"
buildCommand = "npm --prefix backend install --omit=dev"

[deploy]
startCommand = "npm --prefix backend run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
